create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to admin;

create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to admin;

create table auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table auth_permission
    owner to admin;

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

create table auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table auth_group
    owner to admin;

create index auth_group_name_a6ea08ec_like
    on auth_group (name varchar_pattern_ops);

create table auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table auth_group_permissions
    owner to admin;

create index auth_group_permissions_group_id_b120cbf9
    on auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on auth_group_permissions (permission_id);

create table users_user
(
    id           bigint generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null,
    email        varchar(254)             not null
        unique,
    credits      integer                  not null
        constraint users_user_credits_check
            check (credits >= 0)
);

alter table users_user
    owner to admin;

create index users_user_username_06e46fe6_like
    on users_user (username varchar_pattern_ops);

create index users_user_email_243f6e77_like
    on users_user (email varchar_pattern_ops);

create table users_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  bigint  not null
        constraint users_user_groups_user_id_5f6f5a90_fk_users_user_id
            references users_user
            deferrable initially deferred,
    group_id integer not null
        constraint users_user_groups_group_id_9afc8d0e_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint users_user_groups_user_id_group_id_b88eab82_uniq
        unique (user_id, group_id)
);

alter table users_user_groups
    owner to admin;

create index users_user_groups_user_id_5f6f5a90
    on users_user_groups (user_id);

create index users_user_groups_group_id_9afc8d0e
    on users_user_groups (group_id);

create table users_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       bigint  not null
        constraint users_user_user_permissions_user_id_20aca447_fk_users_user_id
            references users_user
            deferrable initially deferred,
    permission_id integer not null
        constraint users_user_user_perm_permission_id_0b93982e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint users_user_user_permissions_user_id_permission_id_43338c45_uniq
        unique (user_id, permission_id)
);

alter table users_user_user_permissions
    owner to admin;

create index users_user_user_permissions_user_id_20aca447
    on users_user_user_permissions (user_id);

create index users_user_user_permissions_permission_id_0b93982e
    on users_user_user_permissions (permission_id);

create table django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         bigint                   not null
        constraint django_admin_log_user_id_c564eba6_fk_users_user_id
            references users_user
            deferrable initially deferred
);

alter table django_admin_log
    owner to admin;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

create table authtoken_token
(
    key     varchar(40)              not null
        primary key,
    created timestamp with time zone not null,
    user_id bigint                   not null
        unique
        constraint authtoken_token_user_id_35299eff_fk_users_user_id
            references users_user
            deferrable initially deferred
);

alter table authtoken_token
    owner to admin;

create index authtoken_token_key_10f0b77e_like
    on authtoken_token (key varchar_pattern_ops);

create table django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table django_session
    owner to admin;

create index django_session_session_key_c0390e0f_like
    on django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on django_session (expire_date);

create table adventures_adventure
(
    id                      bigint generated by default as identity
        primary key,
    is_template             boolean                  not null,
    title                   text                     not null,
    description             text                     not null,
    intro                   text                     not null,
    spec_instructions       text                     not null,
    created_at              timestamp with time zone not null,
    updated_at              timestamp with time zone not null,
    author_user_id          bigint                   not null
        constraint adventures_adventure_author_user_id_fb7042ac_fk_users_user_id
            references users_user
            deferrable initially deferred,
    player_user_id          bigint
        constraint adventures_adventure_player_user_id_eefe2df4_fk_users_user_id
            references users_user
            deferrable initially deferred,
    template_adventure_id   bigint
        constraint adventures_adventure_template_adventure_i_395afdb8_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    primary_hero_id         bigint,
    is_waiting_ai           boolean                  not null,
    rollback_min_history_id bigint,
    constraint adventures_template_or_run_chk
        check ((is_template AND (player_user_id IS NULL) AND (template_adventure_id IS NULL)) OR
               ((NOT is_template) AND (player_user_id IS NOT NULL) AND (template_adventure_id IS NOT NULL)))
);

alter table adventures_adventure
    owner to admin;

create index adventures_adventure_author_user_id_fb7042ac
    on adventures_adventure (author_user_id);

create index adventures_adventure_player_user_id_eefe2df4
    on adventures_adventure (player_user_id);

create index adventures_adventure_template_adventure_id_395afdb8
    on adventures_adventure (template_adventure_id);

create index idx_adventures_player
    on adventures_adventure (player_user_id)
    where (NOT is_template);

create index idx_adventures_template
    on adventures_adventure (is_template);

create index adventures_adventure_primary_hero_id_ed8161c1
    on adventures_adventure (primary_hero_id);

create table adventures_faction
(
    id           bigint generated by default as identity
        primary key,
    title        text                     not null,
    description  text                     not null,
    tags         text[]                   not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_faction_adventure_id_7c93dabf_fk_adventure
            references adventures_adventure
            deferrable initially deferred
);

alter table adventures_faction
    owner to admin;

create index adventures_faction_adventure_id_7c93dabf
    on adventures_faction (adventure_id);

create index idx_factions_tags_gin
    on adventures_faction using gin (tags);

create table adventures_location
(
    id           bigint generated by default as identity
        primary key,
    title        text                     not null,
    description  text                     not null,
    x            integer                  not null,
    y            integer                  not null,
    width        integer                  not null
        constraint locations_width_gt_zero
            check (width > 0),
    height       integer                  not null
        constraint locations_height_gt_zero
            check (height > 0),
    tags         text[]                   not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_location_adventure_id_769dd737_fk_adventure
            references adventures_adventure
            deferrable initially deferred
);

alter table adventures_location
    owner to admin;

create index adventures_location_adventure_id_769dd737
    on adventures_location (adventure_id);

create index idx_locations_adv_xy
    on adventures_location (adventure_id, x, y);

create index idx_locations_tags_gin
    on adventures_location using gin (tags);

create table adventures_otherinfo
(
    id           bigint generated by default as identity
        primary key,
    category     text                     not null,
    title        text                     not null,
    description  text                     not null,
    tags         text[]                   not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_otherinfo_adventure_id_19a4c3e0_fk_adventure
            references adventures_adventure
            deferrable initially deferred
);

alter table adventures_otherinfo
    owner to admin;

create index adventures_otherinfo_adventure_id_19a4c3e0
    on adventures_otherinfo (adventure_id);

create index idx_other_info_category
    on adventures_otherinfo (adventure_id, category);

create index idx_other_info_tags_gin
    on adventures_otherinfo using gin (tags);

create table adventures_race
(
    id           bigint generated by default as identity
        primary key,
    title        text                     not null,
    description  text                     not null,
    tags         text[]                   not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_race_adventure_id_abd1ab03_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    life_span    integer                  not null
);

alter table adventures_race
    owner to admin;

create index adventures_race_adventure_id_abd1ab03
    on adventures_race (adventure_id);

create index idx_races_tags_gin
    on adventures_race using gin (tags);

create table adventures_adventurehistory
(
    id           bigint generated by default as identity
        primary key,
    role         text                     not null
        constraint history_role_chk
            check (role = ANY (ARRAY ['user'::text, 'ai'::text, 'system'::text])),
    content      text                     not null,
    metadata     jsonb                    not null,
    created_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_adventure_adventure_id_51b38d0b_fk_adventure
            references adventures_adventure
            deferrable initially deferred
);

alter table adventures_adventurehistory
    owner to admin;

create index adventures_adventurehistory_adventure_id_51b38d0b
    on adventures_adventurehistory (adventure_id);

create index idx_history_adv_entry_desc
    on adventures_adventurehistory (adventure_id asc, id desc);

create table adventures_adventurememory
(
    id           bigint generated by default as identity
        primary key,
    kind         text                     not null
        constraint memories_kind_chk
            check (kind = ANY (ARRAY ['summary'::text, 'fact'::text, 'rule'::text, 'goal'::text])),
    title        text                     not null,
    content      text                     not null,
    importance   integer                  not null,
    tags         text[]                   not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_adventure_adventure_id_83c93aff_fk_adventure
            references adventures_adventure
            deferrable initially deferred
);

alter table adventures_adventurememory
    owner to admin;

create index adventures_adventurememory_adventure_id_83c93aff
    on adventures_adventurememory (adventure_id);

create index idx_memories_adv_importance
    on adventures_adventurememory (adventure_id asc, importance desc);

create index idx_memories_tags_gin
    on adventures_adventurememory using gin (tags);

create table adventures_character
(
    id                  bigint generated by default as identity
        primary key,
    is_player           boolean                  not null,
    title               text                     not null,
    age                 integer
        constraint characters_age_non_negative
            check ((age >= 0) OR (age IS NULL)),
    body_power          integer                  not null
        constraint characters_body_non_negative
            check (body_power >= 0),
    mind_power          integer                  not null
        constraint characters_mind_non_negative
            check (mind_power >= 0),
    will_power          integer                  not null
        constraint characters_will_non_negative
            check (will_power >= 0),
    description         text                     not null,
    tags                text[]                   not null,
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null,
    adventure_id        bigint                   not null
        constraint adventures_character_adventure_id_b35f85d9_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    location_id         bigint
        constraint adventures_character_location_id_4813fe5d_fk_adventure
            references adventures_location
            deferrable initially deferred,
    race_id             bigint
        constraint adventures_character_race_id_952ac4ba_fk_adventures_race_id
            references adventures_race
            deferrable initially deferred,
    in_party            boolean                  not null,
    body_power_progress integer                  not null
        constraint characters_body_progress_range
            check ((body_power_progress >= 0) AND (body_power_progress <= 100)),
    mind_power_progress integer                  not null
        constraint characters_mind_progress_range
            check ((mind_power_progress >= 0) AND (mind_power_progress <= 100)),
    will_power_progress integer                  not null
        constraint characters_will_progress_range
            check ((will_power_progress >= 0) AND (will_power_progress <= 100))
);

alter table adventures_character
    owner to admin;

alter table adventures_adventure
    add constraint adventures_adventure_primary_hero_id_ed8161c1_fk_adventure
        foreign key (primary_hero_id) references adventures_character
            deferrable initially deferred;

create index adventures_character_adventure_id_b35f85d9
    on adventures_character (adventure_id);

create index adventures_character_location_id_4813fe5d
    on adventures_character (location_id);

create index adventures_character_race_id_952ac4ba
    on adventures_character (race_id);

create index idx_characters_adv_location
    on adventures_character (adventure_id, location_id);

create index idx_characters_is_player
    on adventures_character (adventure_id, is_player);

create index idx_characters_tags_gin
    on adventures_character using gin (tags);

create index idx_characters_in_party
    on adventures_character (adventure_id, in_party);

create trigger trg_characters_same_adventure_refs
    before insert or update
    on adventures_character
    for each row
execute procedure enforce_character_same_adventure_refs();

create table adventures_characterfaction
(
    id           bigint generated by default as identity
        primary key,
    adventure_id bigint not null
        constraint adventures_character_adventure_id_dc507002_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    character_id bigint not null
        constraint adventures_character_character_id_02fa92ed_fk_adventure
            references adventures_character
            deferrable initially deferred,
    faction_id   bigint not null
        constraint adventures_character_faction_id_6ac35575_fk_adventure
            references adventures_faction
            deferrable initially deferred,
    constraint uq_characters_factions
        unique (adventure_id, character_id, faction_id)
);

alter table adventures_characterfaction
    owner to admin;

create index adventures_characterfaction_adventure_id_dc507002
    on adventures_characterfaction (adventure_id);

create index adventures_characterfaction_character_id_02fa92ed
    on adventures_characterfaction (character_id);

create index adventures_characterfaction_faction_id_6ac35575
    on adventures_characterfaction (faction_id);

create index idx_characters_factions_adv
    on adventures_characterfaction (adventure_id);

create trigger trg_characters_factions_same_adventure
    before insert or update
    on adventures_characterfaction
    for each row
execute procedure enforce_character_faction_same_adventure();

create table adventures_characterrelationship
(
    id                bigint generated by default as identity
        primary key,
    kind              text                     not null,
    description       text                     not null,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    adventure_id      bigint                   not null
        constraint adventures_character_adventure_id_1a75dfe7_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    from_character_id bigint                   not null
        constraint adventures_character_from_character_id_15ffa334_fk_adventure
            references adventures_character
            deferrable initially deferred,
    to_character_id   bigint                   not null
        constraint adventures_character_to_character_id_2db22408_fk_adventure
            references adventures_character
            deferrable initially deferred,
    constraint uq_relationship
        unique (adventure_id, from_character_id, to_character_id, kind),
    constraint rel_not_self
        check (NOT (from_character_id = to_character_id))
);

alter table adventures_characterrelationship
    owner to admin;

create index adventures_characterrelationship_adventure_id_1a75dfe7
    on adventures_characterrelationship (adventure_id);

create index adventures_characterrelationship_from_character_id_15ffa334
    on adventures_characterrelationship (from_character_id);

create index adventures_characterrelationship_to_character_id_2db22408
    on adventures_characterrelationship (to_character_id);

create index idx_rel_from
    on adventures_characterrelationship (adventure_id, from_character_id);

create index idx_rel_to
    on adventures_characterrelationship (adventure_id, to_character_id);

create index idx_rel_kind
    on adventures_characterrelationship (adventure_id, kind);

create trigger trg_relationships_same_adventure
    before insert or update
    on adventures_characterrelationship
    for each row
execute procedure enforce_relationship_same_adventure();

create table adventures_skillsystem
(
    id           bigint generated by default as identity
        primary key,
    title        text                     not null,
    description  text                     not null,
    tags         text[]                   not null,
    w_body       integer                  not null,
    w_mind       integer                  not null,
    w_will       integer                  not null,
    formula_hint text                     not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_skillsyst_adventure_id_1fa42538_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    constraint skill_systems_weights_nonneg
        check ((w_body >= 0) AND (w_mind >= 0) AND (w_will >= 0)),
    constraint skill_systems_weights_not_all_zero
        check ((w_body > 0) OR (w_mind > 0) OR (w_will > 0))
);

alter table adventures_skillsystem
    owner to admin;

create index adventures_skillsystem_adventure_id_1fa42538
    on adventures_skillsystem (adventure_id);

create index idx_skill_systems_adv
    on adventures_skillsystem (adventure_id);

create index idx_skill_systems_tags_gin
    on adventures_skillsystem using gin (tags);

create table adventures_technique
(
    id                    bigint generated by default as identity
        primary key,
    title                 text                     not null,
    description           text                     not null,
    tags                  text[]                   not null,
    difficulty            integer                  not null
        constraint techniques_difficulty_nonneg
            check (difficulty >= 0),
    tier                  integer
        constraint techniques_tier_nonneg
            check ((tier >= 0) OR (tier IS NULL)),
    required_system_level integer                  not null
        constraint techniques_required_level_nonneg
            check (required_system_level >= 0),
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    adventure_id          bigint                   not null
        constraint adventures_technique_adventure_id_62626f30_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    system_id             bigint                   not null
        constraint adventures_technique_system_id_71c51bd1_fk_adventure
            references adventures_skillsystem
            deferrable initially deferred
);

alter table adventures_technique
    owner to admin;

create index adventures_technique_adventure_id_62626f30
    on adventures_technique (adventure_id);

create index adventures_technique_system_id_71c51bd1
    on adventures_technique (system_id);

create index idx_techniques_adv_system
    on adventures_technique (adventure_id, system_id);

create index idx_techniques_tags_gin
    on adventures_technique using gin (tags);

create trigger trg_techniques_same_adventure_system
    before insert or update
    on adventures_technique
    for each row
execute procedure enforce_technique_same_adventure_as_system();

create table adventures_charactersystem
(
    id               bigint generated by default as identity
        primary key,
    level            integer not null
        constraint character_system_level_nonneg
            check (level >= 0),
    notes            text    not null,
    adventure_id     bigint  not null
        constraint adventures_character_adventure_id_306f307b_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    character_id     bigint  not null
        constraint adventures_character_character_id_903681e0_fk_adventure
            references adventures_character
            deferrable initially deferred,
    system_id        bigint  not null
        constraint adventures_character_system_id_3792f8f7_fk_adventure
            references adventures_skillsystem
            deferrable initially deferred,
    progress_percent integer not null
        constraint character_system_progress_pct
            check ((progress_percent >= 0) AND (progress_percent <= 100)),
    constraint uq_character_system
        unique (adventure_id, character_id, system_id)
);

alter table adventures_charactersystem
    owner to admin;

create index adventures_charactersystem_adventure_id_306f307b
    on adventures_charactersystem (adventure_id);

create index adventures_charactersystem_character_id_903681e0
    on adventures_charactersystem (character_id);

create index adventures_charactersystem_system_id_3792f8f7
    on adventures_charactersystem (system_id);

create index idx_character_systems_adv
    on adventures_charactersystem (adventure_id);

create trigger trg_character_systems_same_adventure
    before insert or update
    on adventures_charactersystem
    for each row
execute procedure enforce_character_system_same_adventure();

create table adventures_charactertechnique
(
    id           bigint generated by default as identity
        primary key,
    learned_at   timestamp with time zone not null,
    notes        text                     not null,
    adventure_id bigint                   not null
        constraint adventures_character_adventure_id_c08d1b7b_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    character_id bigint                   not null
        constraint adventures_character_character_id_00f23555_fk_adventure
            references adventures_character
            deferrable initially deferred,
    technique_id bigint                   not null
        constraint adventures_character_technique_id_5d2ea09b_fk_adventure
            references adventures_technique
            deferrable initially deferred,
    constraint uq_character_technique
        unique (adventure_id, character_id, technique_id)
);

alter table adventures_charactertechnique
    owner to admin;

create index adventures_charactertechnique_adventure_id_c08d1b7b
    on adventures_charactertechnique (adventure_id);

create index adventures_charactertechnique_character_id_00f23555
    on adventures_charactertechnique (character_id);

create index adventures_charactertechnique_technique_id_5d2ea09b
    on adventures_charactertechnique (technique_id);

create index idx_character_techniques_adv
    on adventures_charactertechnique (adventure_id);

create trigger trg_character_techniques_same_adventure
    before insert or update
    on adventures_charactertechnique
    for each row
execute procedure enforce_character_technique_same_adventure();

create table adventures_adventureevent
(
    id           bigint generated by default as identity
        primary key,
    status       text                     not null
        constraint events_status_chk
            check (status = ANY (ARRAY ['inactive'::text, 'active'::text, 'resolved'::text])),
    title        text                     not null,
    trigger_hint text                     not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    adventure_id bigint                   not null
        constraint adventures_adventure_adventure_id_2c9e8aa4_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    location_id  bigint
        constraint adventures_adventure_location_id_0ec44793_fk_adventure
            references adventures_location
            deferrable initially deferred,
    state        text                     not null
);

alter table adventures_adventureevent
    owner to admin;

create index adventures_adventureevent_adventure_id_2c9e8aa4
    on adventures_adventureevent (adventure_id);

create index adventures_adventureevent_location_id_0ec44793
    on adventures_adventureevent (location_id);

create index idx_events_adv_status
    on adventures_adventureevent (adventure_id, status);

create index idx_events_adv_loc_status
    on adventures_adventureevent (adventure_id, location_id, status);

create table adventures_adventureherosetup
(
    id                  bigint generated by default as identity
        primary key,
    require_race        boolean not null,
    require_age         boolean not null,
    require_body_power  boolean not null,
    require_mind_power  boolean not null,
    require_will_power  boolean not null,
    require_systems     boolean not null,
    require_techniques  boolean not null,
    adventure_id        bigint  not null
        unique
        constraint adventures_adventure_adventure_id_2da372ec_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    default_race_id     bigint
        constraint adventures_adventure_default_race_id_623daa87_fk_adventure
            references adventures_race
            deferrable initially deferred,
    default_age         integer
        constraint hero_setup_default_age_nonneg
            check ((default_age >= 0) OR (default_age IS NULL)),
    default_body_power  integer
        constraint hero_setup_default_body_nonneg
            check ((default_body_power >= 0) OR (default_body_power IS NULL)),
    default_mind_power  integer
        constraint hero_setup_default_mind_nonneg
            check ((default_mind_power >= 0) OR (default_mind_power IS NULL)),
    default_will_power  integer
        constraint hero_setup_default_will_nonneg
            check ((default_will_power >= 0) OR (default_will_power IS NULL)),
    default_location_id bigint
        constraint adventures_adventure_default_location_id_03ed22a2_fk_adventure
            references adventures_location
            deferrable initially deferred
);

alter table adventures_adventureherosetup
    owner to admin;

create index idx_hero_setup_adv
    on adventures_adventureherosetup (adventure_id);

create index adventures_adventureherosetup_default_race_id_623daa87
    on adventures_adventureherosetup (default_race_id);

create index adventures_adventureherosetup_default_location_id_03ed22a2
    on adventures_adventureherosetup (default_location_id);

create table users_administrator
(
    id      bigint generated by default as identity
        primary key,
    level   smallint not null
        constraint users_administrator_level_check
            check (level >= 0),
    user_id bigint   not null
        unique
        constraint users_administrator_user_id_b4ab1dd1_fk_users_user_id
            references users_user
            deferrable initially deferred
);

alter table users_administrator
    owner to admin;

create table adventures_moderationentry
(
    adventure_id bigint                   not null
        primary key
        constraint adventures_moderatio_adventure_id_0d9a1072_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    submitted_at timestamp with time zone not null
);

alter table adventures_moderationentry
    owner to admin;

create table adventures_publishedadventure
(
    adventure_id bigint                   not null
        primary key
        constraint adventures_published_adventure_id_18941941_fk_adventure
            references adventures_adventure
            deferrable initially deferred,
    published_at timestamp with time zone not null
);

alter table adventures_publishedadventure
    owner to admin;

