"""
URL configurations for the adventures app.
"""
from django.urls import path

from .views import (
    AdventureTemplateDetailView,
    AdventureTemplateListCreateView,
    AdventureEventDetailView,
    AdventureEventListCreateView,
    AdventureTemplateExportView,
    AdventureTemplateImportView,
    AdventureRunBootstrapView,
    AdventureRunCharactersView,
    AdventureRunHeroSetupView,
    AdventureRunHistoryView,
    AdventureRunHistoryGenerateView,
    AdventureRunHeroPromptView,
    AdventureRunHistoryRollbackView,
    AdventureRunHistoryRegenerateView,
    AdventureRunListView,
    AdventureRunStartView,
    AdventureRunDetailView,
    AdventureRunHistoryPdfView,
    AdventureHeroSetupDetailView,
    ModerationQueueListView,
    PublishedAdventureListView,
    AdventureSubmitForModerationView,
    ModerationDecisionView,
    CharacterSystemDetailView,
    CharacterSystemListCreateView,
    CharacterTechniqueDetailView,
    CharacterTechniqueListCreateView,
    CharacterDetailView,
    CharacterListCreateView,
    FactionDetailView,
    FactionListCreateView,
    LocationDetailView,
    LocationListCreateView,
    OtherInfoDetailView,
    OtherInfoListCreateView,
    RaceDetailView,
    RaceListCreateView,
    SkillSystemDetailView,
    SkillSystemListCreateView,
    TechniqueDetailView,
    TechniqueListCreateView,
)


urlpatterns = [
    path("templates/", AdventureTemplateListCreateView.as_view(), name="adventure_templates"),
    path(
        "templates/<int:pk>/",
        AdventureTemplateDetailView.as_view(),
        name="adventure_template_detail",
    ),
    path(
        "templates/<int:template_id>/locations/",
        LocationListCreateView.as_view(),
        name="adventure_locations",
    ),
    path(
        "templates/<int:template_id>/locations/<int:pk>/",
        LocationDetailView.as_view(),
        name="adventure_location_detail",
    ),
    path(
        "templates/<int:template_id>/races/",
        RaceListCreateView.as_view(),
        name="adventure_races",
    ),
    path(
        "templates/<int:template_id>/races/<int:pk>/",
        RaceDetailView.as_view(),
        name="adventure_race_detail",
    ),
    path(
        "templates/<int:template_id>/systems/",
        SkillSystemListCreateView.as_view(),
        name="adventure_systems",
    ),
    path(
        "templates/<int:template_id>/systems/<int:pk>/",
        SkillSystemDetailView.as_view(),
        name="adventure_system_detail",
    ),
    path(
        "templates/<int:template_id>/techniques/",
        TechniqueListCreateView.as_view(),
        name="adventure_techniques",
    ),
    path(
        "templates/<int:template_id>/techniques/<int:pk>/",
        TechniqueDetailView.as_view(),
        name="adventure_technique_detail",
    ),
    path(
        "templates/<int:template_id>/factions/",
        FactionListCreateView.as_view(),
        name="adventure_factions",
    ),
    path(
        "templates/<int:template_id>/factions/<int:pk>/",
        FactionDetailView.as_view(),
        name="adventure_faction_detail",
    ),
    path(
        "templates/<int:template_id>/other-info/",
        OtherInfoListCreateView.as_view(),
        name="adventure_other_info",
    ),
    path(
        "templates/<int:template_id>/other-info/<int:pk>/",
        OtherInfoDetailView.as_view(),
        name="adventure_other_info_detail",
    ),
    path(
        "templates/<int:template_id>/characters/",
        CharacterListCreateView.as_view(),
        name="adventure_characters",
    ),
    path(
        "templates/<int:template_id>/characters/<int:pk>/",
        CharacterDetailView.as_view(),
        name="adventure_character_detail",
    ),
    path(
        "templates/<int:template_id>/character-systems/",
        CharacterSystemListCreateView.as_view(),
        name="adventure_character_systems",
    ),
    path(
        "templates/<int:template_id>/character-systems/<int:pk>/",
        CharacterSystemDetailView.as_view(),
        name="adventure_character_system_detail",
    ),
    path(
        "templates/<int:template_id>/character-techniques/",
        CharacterTechniqueListCreateView.as_view(),
        name="adventure_character_techniques",
    ),
    path(
        "templates/<int:template_id>/character-techniques/<int:pk>/",
        CharacterTechniqueDetailView.as_view(),
        name="adventure_character_technique_detail",
    ),
    path(
        "templates/<int:template_id>/events/",
        AdventureEventListCreateView.as_view(),
        name="adventure_events",
    ),
    path(
        "templates/<int:template_id>/events/<int:pk>/",
        AdventureEventDetailView.as_view(),
        name="adventure_event_detail",
    ),
    path(
        "templates/<int:template_id>/export/",
        AdventureTemplateExportView.as_view(),
        name="adventure_template_export",
    ),
    path(
        "templates/import/",
        AdventureTemplateImportView.as_view(),
        name="adventure_template_import",
    ),
    path(
        "templates/<int:template_id>/start/",
        AdventureRunStartView.as_view(),
        name="adventure_run_start",
    ),
    path(
        "templates/<int:template_id>/hero-setup/",
        AdventureHeroSetupDetailView.as_view(),
        name="adventure_hero_setup",
    ),
    path(
        "templates/<int:template_id>/submit/",
        AdventureSubmitForModerationView.as_view(),
        name="adventure_submit_for_moderation",
    ),
    path(
        "moderation/queue/",
        ModerationQueueListView.as_view(),
        name="adventure_moderation_queue",
    ),
    path(
        "moderation/published/",
        PublishedAdventureListView.as_view(),
        name="adventure_published_list",
    ),
    path(
        "moderation/<int:template_id>/<str:decision>/",
        ModerationDecisionView.as_view(),
        name="adventure_moderation_decision",
    ),
    path(
        "runs/",
        AdventureRunListView.as_view(),
        name="adventure_runs",
    ),
    path(
        "runs/<int:pk>/",
        AdventureRunDetailView.as_view(),
        name="adventure_run_detail",
    ),
    path(
        "runs/<int:run_id>/bootstrap/",
        AdventureRunBootstrapView.as_view(),
        name="adventure_run_bootstrap",
    ),
    path(
        "runs/<int:run_id>/hero/",
        AdventureRunHeroSetupView.as_view(),
        name="adventure_run_hero",
    ),
    path(
        "runs/<int:run_id>/history/",
        AdventureRunHistoryView.as_view(),
        name="adventure_run_history",
    ),
    path(
        "runs/<int:run_id>/history/pdf/",
        AdventureRunHistoryPdfView.as_view(),
        name="adventure_run_history_pdf",
    ),
    path(
        "runs/<int:run_id>/history/next/",
        AdventureRunHistoryGenerateView.as_view(),
        name="adventure_run_history_next",
    ),
    path(
        "runs/<int:run_id>/history/hero/",
        AdventureRunHeroPromptView.as_view(),
        name="adventure_run_history_hero",
    ),
    path(
        "runs/<int:run_id>/history/<int:entry_id>/rollback/",
        AdventureRunHistoryRollbackView.as_view(),
        name="adventure_run_history_rollback",
    ),
    path(
        "runs/<int:run_id>/history/last/regenerate/",
        AdventureRunHistoryRegenerateView.as_view(),
        name="adventure_run_history_regenerate",
    ),
    path(
        "runs/<int:run_id>/characters/",
        CharacterListCreateView.as_view(),
        name="adventure_run_characters",
    ),
    path(
        "runs/<int:run_id>/characters/party/",
        AdventureRunCharactersView.as_view(),
        name="adventure_run_party_characters",
    ),
    path(
        "runs/<int:run_id>/locations/",
        LocationListCreateView.as_view(),
        name="adventure_run_locations",
    ),
    path(
        "runs/<int:run_id>/locations/<int:pk>/",
        LocationDetailView.as_view(),
        name="adventure_run_location_detail",
    ),
    path(
        "runs/<int:run_id>/races/",
        RaceListCreateView.as_view(),
        name="adventure_run_races",
    ),
    path(
        "runs/<int:run_id>/races/<int:pk>/",
        RaceDetailView.as_view(),
        name="adventure_run_race_detail",
    ),
    path(
        "runs/<int:run_id>/systems/",
        SkillSystemListCreateView.as_view(),
        name="adventure_run_systems",
    ),
    path(
        "runs/<int:run_id>/systems/<int:pk>/",
        SkillSystemDetailView.as_view(),
        name="adventure_run_system_detail",
    ),
    path(
        "runs/<int:run_id>/techniques/",
        TechniqueListCreateView.as_view(),
        name="adventure_run_techniques",
    ),
    path(
        "runs/<int:run_id>/techniques/<int:pk>/",
        TechniqueDetailView.as_view(),
        name="adventure_run_technique_detail",
    ),
    path(
        "runs/<int:run_id>/factions/",
        FactionListCreateView.as_view(),
        name="adventure_run_factions",
    ),
    path(
        "runs/<int:run_id>/factions/<int:pk>/",
        FactionDetailView.as_view(),
        name="adventure_run_faction_detail",
    ),
    path(
        "runs/<int:run_id>/other-info/",
        OtherInfoListCreateView.as_view(),
        name="adventure_run_other_info",
    ),
    path(
        "runs/<int:run_id>/other-info/<int:pk>/",
        OtherInfoDetailView.as_view(),
        name="adventure_run_other_info_detail",
    ),
    path(
        "runs/<int:run_id>/characters/<int:pk>/",
        CharacterDetailView.as_view(),
        name="adventure_run_character_detail",
    ),
    path(
        "runs/<int:run_id>/character-systems/",
        CharacterSystemListCreateView.as_view(),
        name="adventure_run_character_systems",
    ),
    path(
        "runs/<int:run_id>/character-systems/<int:pk>/",
        CharacterSystemDetailView.as_view(),
        name="adventure_run_character_system_detail",
    ),
    path(
        "runs/<int:run_id>/character-techniques/",
        CharacterTechniqueListCreateView.as_view(),
        name="adventure_run_character_techniques",
    ),
    path(
        "runs/<int:run_id>/character-techniques/<int:pk>/",
        CharacterTechniqueDetailView.as_view(),
        name="adventure_run_character_technique_detail",
    ),
    path(
        "runs/<int:run_id>/events/",
        AdventureEventListCreateView.as_view(),
        name="adventure_run_events",
    ),
    path(
        "runs/<int:run_id>/events/<int:pk>/",
        AdventureEventDetailView.as_view(),
        name="adventure_run_event_detail",
    ),
]
